### ISSUE TITLE
CI fails when package index of runner is out of date

### ISSUE THREAD

**Issue by kawaiiPlat** [uf-mil/mil#1000]
### Assignee

@kawaiiPlat

### What needs to change?

Package index needs to be updated before upgrade or install is run in the CI container.

![image](https://user-images.githubusercontent.com/50600614/223797552-39da436c-40d2-49e3-9124-ad31263eb54f.png)

### How would this task be tested?

1. CI build will complete without the current intermittent 404 to resolve outdated package index entries.

### Contacts

- [ ] We need help from the mechanical team.
- [ ] We need help from the electrical team.
- [ ] We need help from Dr. Schwartz or other faculty.
- [ ] We need help from a company or an organization.
- [ ] We need help from another UF staff member or organization (ex, facilities).

**Comment by cbrxyz** [comment]
Closed in #1001, thanks Jarrod!
