### ISSUE TITLE
Develop Python library to YOLOv7 interface

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#1030]
### What needs to change?

When YOLOv7 has been used by the lab in the past, we have traditionally just gained information from the data it outputs to its topics. We should change this by creating a helper Python library that makes it easier to discern what information is being sent out by the system.

This library could:
* Create helper functions for getting object detection information
* Define and raise a set of exceptions as a result of certain criteria being met (for example, raising an exception when no objects are found, but are requested)
* Create classes to store information about found objects, and classes for the queries themselves

### How would this task be tested?

1. You can write simple tests to test the Python library in a variety of circumstances (when an object is found, when no object is found, etc).

### Contacts

- [ ] We need help from the mechanical team.
- [ ] We need help from the electrical team.
- [ ] We need help from Dr. Schwartz or other faculty.
- [ ] We need help from a company or an organization.
- [ ] We need help from another UF staff member or organization (ex, facilities).

**Comment by MrinallU** [comment]
PR made is yolov7 node repository: https://github.com/uf-mil/yolov7-ros/pull/2
