### ISSUE TITLE
Sub9 Navigation Tube ROS Client

### ISSUE THREAD

**Issue by andrew-aj** [uf-mil/mil#1123]
### What needs to change?

This task involves writing a TCP client that will connect to the TCP server on the Raspberry Pi in #1121. It will use the common communication protocol developed in #1120. Using the data obtained from the multiplexer, it will publish it to the corresponding ROS topics.

### How would this task be tested?

1. TCP client connects to TCP server successfully
2. Verify correct interpretation of communication protocol with unit tests
3. Verify real time data output to ROS

### Contacts

- [ ] We need help from the mechanical team.
- [ ] We need help from the electrical team.
- [ ] We need help from Dr. Schwartz or other faculty.
- [ ] We need help from a company or an organization.
- [x] We need help from another UF staff member or organization (ex, facilities).

**Comment by MkMayo** [comment]
Wrote a Client that can connect with the server Sebastian wrote and communicate with it.
