### ISSUE TITLE
Develop vision pipeline for RoboSub 2023 objects

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#1125]
### What needs to change?

This task involves developing a complete model for identifying the various RoboSub 2023 models. This model should have a high level of accuracy in identifying:

* Start Gate glyphs
* Buoy glyphs
* Bin images
* Torpedos images

This model will then be able to be used in missions tasks.

### How would this task be tested?

1. Train a model and test its accuracy. Ensure that the training accuracy is relatively high. 
2. Test the model in a real-world environment.

### Contacts

- [ ] We need help from the mechanical team.
- [ ] We need help from the electrical team.
- [ ] We need help from Dr. Schwartz or other faculty.
- [ ] We need help from a company or an organization.
- [ ] We need help from another UF staff member or organization (ex, facilities).

**Comment by AlexanderWangY** [comment]
I can help with this :smile:
