### ISSUE TITLE
Complete 2023 buoys mission code

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#1129]
### What needs to change?

We will need to setup the buoys mission from RoboSub 2023. This will need to:

* Locate the buoys in the water in the surrounding environment (will require vision models to be fully completed, but in testing, can be done by hardcoding the position of the buoys in the relative environment)
* Rotate towards the buoys in the water
* Move forward until the sub touches the buoys

### How would this task be tested?

1.
2.
3.

### Contacts

- [ ] We need help from the mechanical team.
- [ ] We need help from the electrical team.
- [ ] We need help from Dr. Schwartz or other faculty.
- [ ] We need help from a company or an organization.
- [ ] We need help from another UF staff member or organization (ex, facilities).

**Comment by MrinallU** [comment]
I can help out with this as well.
