### ISSUE TITLE
Robosub 2024: Enter the Pacific | Gate

### ISSUE THREAD

**Issue by DaniParr** [uf-mil/mil#1142]
### What needs to change?

Choose direction and ocean temperature
• Clockwise (CW) / Hot (Red)
• Counter clockwise (CCW) / Cold (Blue)

**EXTRA (Recommended):**
• 10 ft/3 m before/after gate
• Extra points

  • Every 90° change in orientation
      • Yaw: +100
      • Roll/Pitch: +200
      
  • Up to 720° rotation
      • Yaw: +800
      • Roll/Pitch: +1600
    
 
![image](https://github.com/uf-mil/mil/assets/74571960/9285ef56-752a-42ed-bc5e-9f92530fb345)

### How would this task be tested?

1. Add your mission object to ../Subjugator/command/subjugator_missions/subjugator_missions/__init__.py
2. Run `roslaunch subjugator_launch gazebo.launch`
3. Run `gazebogui`
4. Run `mission run <NameOfMission>`

### Contacts

- [ ] We need help from the mechanical team.
- [ ] We need help from the electrical team.
- [ ] We need help from Dr. Schwartz or other faculty.
- [ ] We need help from a company or an organization.
- [ ] We need help from another UF staff member or organization (ex, facilities).

**Comment by cbrxyz** [comment]
Will be completed in https://github.com/uf-mil/mil/pull/1164 once merged in
