### ISSUE TITLE
Robosub 2024: Hydrothermal Vent | Buoy

### ISSUE THREAD

**Issue by DaniParr** [uf-mil/mil#1143]
### What needs to change?

There will be a single RED buoy:
- Have the sub circumnavigate the buoy (either CW or CCW)

![image](https://github.com/uf-mil/mil/assets/74571960/4de977f5-6d67-4310-8dd5-8c986cf111e9)

### How would this task be tested?

1. Add your mission object to ../Subjugator/command/subjugator_missions/subjugator_missions/init.py
2. Run `roslaunch subjugator_launch gazebo.launch`
3. Run `gazebogui`
4. Run `mission run <NameOfMission>`

### Contacts

- [ ] We need help from the mechanical team.
- [ ] We need help from the electrical team.
- [ ] We need help from Dr. Schwartz or other faculty.
- [ ] We need help from a company or an organization.
- [ ] We need help from another UF staff member or organization (ex, facilities).

**Comment by tjcanro** [comment]
I'll give this a shot
