### ISSUE TITLE
Sample Type (Coral, Sea Star, Tube Worm) Detection

### ISSUE THREAD

**Issue by DaniParr** [uf-mil/mil#1182]
### What needs to change?

Train a YOLOv7 model that can detect whether a pvc structure is a tube worm, sea star, or coral. (We have the props in lab but we are waiting on the bag data).

Once you have trained your model, create a node that publishes an image of the bounding boxes over the raw footage.

### How would this task be tested?

1. Run Gazebo
2. Make sure the detections are correct

### Contacts

- [ ] We need help from the mechanical team.
- [ ] We need help from the electrical team.
- [ ] We need help from Dr. Schwartz or other faculty.
- [ ] We need help from a company or an organization.
- [ ] We need help from another UF staff member or organization (ex, facilities).

**Comment by useyourshadow** [comment]
-Ignore development opened
