### ISSUE TITLE
Document Net box

### ISSUE THREAD

**Issue by MarshallRawson** [uf-mil/mil#124]
The Network box is in a non-functional state. When plugged into SubjuGator, there is a yellow status LED on the ethernet connection, but no green LED indicating network connection. Also, the netbox needs to be documented so in the future if it needs to be fixed / replaced, we have a reference.

**Comment by kev-the-dev** [comment]
With regards to the "fix" part... How do you know this is the net box issue not SubjuGator issue? Especially if your local machine or others can get a dhcp lease and connect to the router

**Comment by MarshallRawson** [comment]
> With regards to the "fix" part... How do you know this is the net box issue not SubjuGator issue? Especially if your local machine or others can get a dhcp lease and connect to the router

Using a different router, the sub was giving the green LED and visible on network, that is how I got the competition changes on [SubjuGator competition branch](https://github.com/uf-mil/SubjuGator/tree/competition)

**Comment by kev-the-dev** [comment]
Confirmed cannot repro, this is a documentation ticket
