### ISSUE TITLE
RobotX 2024: Task 4 - Wildlife Encounter TEST CASES

### ISSUE THREAD

**Issue by DaniParr** [uf-mil/mil#1263]
### What needs to change?

Write test cases for [Task 4](https://github.com/uf-mil/mil/issues/1255). Create these by modifying existing worlds and saving those world files to be deployed on ROS launch as an argument.

### How would this task be tested?

1. Launch ROS: `roslaunch navigator_launch simulation.launch world:=<name_of_world> --screen`

**Comment by DaniParr** [comment]
@MarcinPlaza @EAOZONE Hey y'all any progress on this issue?

**Comment by EAOZONE** [comment]
> @MarcinPlaza @EAOZONE Hey y'all any progress on this issue?

I'm new and was just figuring things out last week. Plan on working on it this week.

**Comment by MarcinPlaza** [comment]
![Screenshot from 2024-09-13 00-31-46](https://github.com/user-attachments/assets/02a669d2-8f1b-4b54-91a9-1a08135c79e0)
Well I wasted some time trying to make better models, but I ended up just making basic models for the buoys. Here's my understanding of the positioning. I will push to a branch soon. Should I make separate worlds for the different cases randomizing the color order?

**Comment by EAOZONE** [comment]
This week I took the created test case by @MarcinPlaza and made 5 other versions of it with the different color order

**Comment by hoshbosh** [comment]
This week I went through the pr by @DaniParr on my local machine, loading the simulation and reviewing the code.
