### ISSUE TITLE
Merge in competition changes to SubjuGator

### ISSUE THREAD

**Issue by kev-the-dev** [uf-mil/mil#13]
Important changes made to SubjuGator at RoboSub 2019 were not pull requested or merged, and therefore were not included when SubjuGator was merged into the monorepo. 

After reviewing the changes and *cleaning them up for readability*, merge these changes into the monorepo (git should handle this smoothly as the files were moved from the repo)

**Comment by kawaiiPlat** [comment]
Marked stale and closing
