### ISSUE TITLE
CI: enable formating checks

### ISSUE THREAD

**Issue by kev-the-dev** [uf-mil/mil#131]
* clang-format for c++
* flake8 for python
* use previous deprecated CI as model
* Provide user scripts / aliases to check manually

**Comment by kev-the-dev** [comment]
C++ is done in #134, still need python

**Comment by cbrxyz** [comment]
CI has changed significantly since this issue was made, and can now be closed due to the addition of the following linters for Python:
- `black`
- `isort`

Manual checking is supported by the `pre-commit` tool. Thanks!
