### ISSUE TITLE
Battery Pod connections

### ISSUE THREAD

**Issue by jaxnb** [uf-mil/mil#162]
Right now, the battery pods have connectors on both sides. All connectors should be on the same side.
Additionally, a battery rail should be designed such that the battery can be slid into the end of the tube without bulkheads, and the anderson connectors are held in place so they mate when the rail is slid all the way in.

**Comment by andrespulido8** [comment]
Is this completed? @jaxnb

**Comment by andrespulido8** [comment]
Was this completed? @MechAnger

**Comment by MechAnger** [comment]
yes, check out the latest Subjugator 9 frame.
