### ISSUE TITLE
script to build docs on windows

### ISSUE THREAD

**Issue by kev-the-dev** [uf-mil/mil#172]
As the mechanic team is now using the monorepo for docs, it would be nice to allow them to generate the docs on Windows.

This should perhaps be combined with a windows setup script that installs python and other docs dependencies

**Comment by cbrxyz** [comment]
Windows is not a supported developer operating system as of now. Supporting Windows is a significant investment, and many (if not most) of our tools assume that our users are based on a Unix computer. We don't feel that this effort is worth it as of now.
