### ISSUE TITLE
Machine and mount new buoyancy foam

### ISSUE THREAD

**Issue by andrespulido8** [uf-mil/mil#179]
Keep same dimension from old foam. Paint them black. Calculate the buoyancy force per unit of volume for the foam so we know the force it is required to maintain the sub slightly positively buoyant

**Comment by andrespulido8** [comment]
Sub right now is negatively buoyant when Imaging Sonar is mounted

**Comment by jaxnb** [comment]
What did we add/remove? I'd say that sub being negatively buoyant in the same state as it was at the competition would be a concern. We should correct this, but also pay close attention to what has changed.

**Comment by andrespulido8** [comment]
Is the new foam purchased already machined and mounted? @MechAnger

**Comment by MechAnger** [comment]
i opened another issue while there was a physical meeting and did  not see this one, i have copied all the comments under "Blue Robotics R-3312 Foam Buoyancy Measure and Cut #284"
