### ISSUE TITLE
Investigate NavBox issues

### ISSUE THREAD

**Issue by kev-the-dev** [uf-mil/mil#180]
At Sub testing 2/9/20, we were unable to communicate with the DVL or depth sensor. Further diagnostics indicate that this is likely a hardware issue.

Prior to leaving MIL, we were able to talk to all sensors.

After getting to the pool, we got no data from IMU, magnetometer, depth sensor, or DVL. After rebooting / changing batteries, the IMU and magnetometer started working but depth and DVL did not. The DVL did send data for a couple of seconds at one point.

We SSHed into the gumstix computer and read directly from the serial devices representing the DVL and depth sensors and received no data. This rules out an issue with the gumstix CPU or networking to the main computer.

**Comment by jaxnb** [comment]
I have some guesses to some of the issues.
I can't remember when, but at some point someone said they opened the nav vessel and may have removed the depth sensor connector from the gumstix carrier board. I know that there are two identical connectors that the depth sensor could be plugged into, but I don't know if it would work in both.
As for the DVL, this intermittent issue brings to mind the serial connector on the dvl computer. It has no retaining mechanism, and it's very possible that it has vibrated off again. We should look for a long term solution to this, but it can be temporarily solved with more hot glue if it is indeed the culprit.
