### ISSUE TITLE
Builds are failing due to "internal compiler error"

### ISSUE THREAD

**Issue by kev-the-dev** [uf-mil/mil#186]
It seems that all CI builds are failing with an "internal compiler error". See [here](https://buildkite.com/uf-mil/mil/builds/553#81fec8be-18d3-40e4-abca-9143e8415b8e/71-3652) for an example. I have seen this before when the server is running out of RAM or disk space... these should be investigated first. Is also a good idea to repro locally within the container

**Comment by MarshallRawson** [comment]
fixed by magic container rebuild
