### ISSUE TITLE
Find solution for front camera PV

### ISSUE THREAD

**Issue by andrespulido8** [uf-mil/mil#191]
The front camera will be located outside of the main pressure vessel (PV). We need a housing solution. It can be either designed or an OTS part (maybe blue robotics tube?).

**Comment by legallyjuan** [comment]
Basically the same as Sub 8 down camera enclosure #3 and add an vent plug on the metal plate.

**Comment by jaxnb** [comment]
Update: We might need stereo cameras. We should plan on this as a possibility.

**Comment by andrespulido8** [comment]
Kip already has a design and is preparing a list to buy all parts
