### ISSUE TITLE
Disable or Fix Flakey Tests

### ISSUE THREAD

**Issue by kev-the-dev** [uf-mil/mil#192]
There are a couple ROS tests in the monorepo which _sometimes_ fail due to timing dependencies which vary based on system load. Ideally, CI would always generate the same results. 

First, identify which tests fail by spying on builds / manually triggering buildkite rebuilds several times. From my memory, they are the sub8_thruster_map test and some ros_alarms hearbeat test. Possibly more.

Next, pick a solution:

* Redesign test to not have timing dependencies. For example, simply test the class / method using a unit test instead of a ROS test (integration test)
* Make timing dependencies MUCH looser so they will not fail even under significant system load. Ideally this is done in a way so it _can_ still complete quickly. For example, wait for a message up to 3 minutes before failing but pass instantly if it comes in before that.
* Simply disable the test if it doesn't seem to cover much or if that funcitonality is covered in another test

**Comment by cbrxyz** [comment]
Fixed
