### ISSUE TITLE
Write Driver for STIM300 IMU

### ISSUE THREAD

**Issue by kev-the-dev** [uf-mil/mil#203]
related to #171 

Write a ROS driver to read the communications from the https://www.sensonor.com/support/stim300/ STIM300 IMU and publish the data to ROS

**Comment by MarshallRawson** [comment]
It seems that this IMU is just a normal imu and we should be able to reuse our current imu simualtion with diffrent params for it.

**Comment by MarshallRawson** [comment]
> It seems that this IMU is just a normal imu and we should be able to reuse our current imu simualtion with diffrent params for it.

Was referencing wrong data sheet

**Comment by cbrxyz** [comment]
No longer being integrated (instead, we are now using the [VN100](https://www.vectornav.com/products/detail/vn-100))
