### ISSUE TITLE
INDY AV: Waypoint Saving Node

### ISSUE THREAD

**Issue by popeyedpanther** [uf-mil/mil#205]
To create a waypoint following software stack we need a node that:
Subscribes:
 - /odom  ([nav_msgs/Odometry](http://docs.ros.org/melodic/api/nav_msgs/html/msg/Odometry.html))

Publishes:
 - none/TBD

Functionality:
The node should subscribe to the /odom topic and at some predefined rate (maybe a param or arg) and save the data to a file, preferably a yaml file. 

The saved data should be at the minimum:
 - Position (2D or 3D?) in meters
 - Velocity (Speed or linear velocity vector?) in meters/second

Notes:
Should be written in C++

**Comment by MarshallRawson** [comment]
I think this node should also save relevent details of the saved path. ie: ECEF of start, date created, and a name(passed in as a param)

**Comment by popeyedpanther** [comment]
As a side note, where should this code go in the repository, It doesn't really fit into the directories I have set up so far. Its more of a utility than a critical part of the waypoint following autonomy.

**Comment by JoshuaSiy** [comment]
How do i assign myself?

**Comment by popeyedpanther** [comment]
I assigned you but on the top right it should say "Assignees", just click the gear and find your account in the list.
