### ISSUE TITLE
INDY AV: Pure Pursuit Node

### ISSUE THREAD

**Issue by patrick-neal** [uf-mil/mil#207]
To create a waypoint following software stack we need a node that:

Subscribes:
- /odom ([nav_msgs/Odometry](http://docs.ros.org/melodic/api/nav_msgs/html/msg/Odometry.html))
- /path ([nav_msgs/Path](http://docs.ros.org/melodic/api/nav_msgs/html/msg/Path.html))

Publishes:
- Steering command (desired front tire angle)?

Functionality:
This node should implement the pure pursuit algorithm.

Notes:
Should work closely with the path loader programmer to ensure compatibility for path data.
Should be written in C++

References:
https://www.coursera.org/lecture/intro-self-driving-cars/lesson-2-geometric-lateral-control-pure-pursuit-44N7x
Check out the original paper from CMU (should be first google result PDF).
Also check out Dr. Crane's work for calculating look ahead point and the ICR.

**Comment by cbrxyz** [comment]
This issue is being closed because the IndyAV project is no longer being developed upon. Thank you for your interest in the project!
