### ISSUE TITLE
INDY AV: Speed Control Node

### ISSUE THREAD

**Issue by patrick-neal** [uf-mil/mil#208]
To create a waypoint following software stack we need a node that:

Subscribes:
- /odom  ([nav_msgs/Odometry](http://docs.ros.org/melodic/api/nav_msgs/html/msg/Odometry.html))
- Waypoint data containing speeds

Publishes:
- Maybe throttle/braking commands (details TBD)

Functionality:
The node should attempt to keep the vehicle at the speed prescribed from the waypoints. This could be done using a form of PID controller. Should include functionality to keep the vehicle tracking a constant speed, maybe defined within launch file as param or argument.

Notes:
Should be done in C++

**Comment by cbrxyz** [comment]
This issue is being closed because the IndyAV project is no longer being developed upon. Thank you for your interest in the project!
