### ISSUE TITLE
indyav gazebo, impliment ackerman steering

### ISSUE THREAD

**Issue by MarshallRawson** [uf-mil/mil#223]
currently, when a steering command is given in the simulator, both wheels go to the same commanded steering angle. This is not what happens in reality. In reality, the go kart uses [Akerman Steering](https://en.wikipedia.org/wiki/Ackermann_steering_geometry). Go implement the ackerman steering in `indyav_control simulated_steering_driver` where appropriate.

**Comment by cbrxyz** [comment]
This issue is being closed because the IndyAV project is no longer being developed upon. Thank you for your interest in the project!
