### ISSUE TITLE
indyav odom estimator

### ISSUE THREAD

**Issue by MarshallRawson** [uf-mil/mil#224]
Currently in indyav, there is no odom estimation, we trust the sensor completely. This is a big problem. In the Indyav project we are going to be using the same localization hardware for the car as we currently do for navigator. The ideal solution is to implement the same odometry estimation system we use for navigator for indyav.

**Comment by cbrxyz** [comment]
This issue is being closed because the IndyAV project is no longer being developed upon. Thank you for your interest in the project!
