### ISSUE TITLE
indyav gazebo, simulate engine delay

### ISSUE THREAD

**Issue by MarshallRawson** [uf-mil/mil#227]
in real life, when we command a throttle from the computer, the command goes to a smart motor that will (almost instantly in this case) move the throttle on the motor to the correct position. but then the engine has a significant amount of time before its power matches the commanded throttle. However, in simulation, we do not simulate this engine input lag. Currently in simulation, we havea thrust plugin that immediately applies the deisred amount of force. Go into `indyav_gazebo backwheel_plugin` and make the output of the plugin match the output of the engine delay.

**Comment by cbrxyz** [comment]
This issue is being closed because the IndyAV project is no longer being developed upon. Thank you for your interest in the project!
