### ISSUE TITLE
indyav gazebo make simulated params of the car the same as the real params

### ISSUE THREAD

**Issue by MarshallRawson** [uf-mil/mil#229]
Currently in gazebo simulation, we use a model informed by parameters that are complete guesses. Go into indyav_gazebo `gokart.xacro` , `wheels.xacro`, and `indyav_car.urdf.xacro` and make the mass, size and placement params match the actual gokart.

**Comment by MihirRao01** [comment]
Here is the measurements for the wheels:
back wheel length : 8.5 in 
back wheel height : 10.5 in
back wheel mass : 2250 g

front wheel length : 5.25 in
front wheel height: 10.25 in
front wheel mass : 1650 g

**Comment by dprestri** [comment]
chassis mass (no wheels, with superstructure, no battery) : 65.3173 
cg at 33.8% from front of vehicle, approximately 8" from ground
