### ISSUE TITLE
Look into replacements for regulators

### ISSUE THREAD

**Issue by andrespulido8** [uf-mil/mil#232]
The regulators for the paintball tank are not available to buy anymore. A need regulator for the paintball tank needs to be bought, or maybe replace all the paintball tanks with a dive tank. needs to buy. Additionally, look for a safety valve with higher pressure threshold for the pneumatic manifold (150psi).

**Comment by MechAnger** [comment]
We will introduce servos from sub 9 and get rid of the valve box and paintball tank. So whoever designs the torpedo launcher and gripper for sub 9 using servos, please also do it for sub 8!

**Comment by andrespulido8** [comment]
Before saying we're getting rid of pneumatics have all the electric actuators manufactured and make sure they are as or more reliable than the pneumatics
