### ISSUE TITLE
License on mil_blueview_driver?

### ISSUE THREAD

**Issue by amarburg** [uf-mil/mil#238]
Hi guys,

I'm interested in forking your mil_blueview_driver to support some of our research.   Have you defined a license for your ROS nodes?   

Thanks!

**Comment by amarburg** [comment]
Ah, noticed in the [package.xml](https://github.com/uf-mil/mil/blob/master/mil_common/drivers/mil_blueview_driver/package.xml) that it's MIT license. That still valid?

**Comment by RustyBamboo** [comment]
#239

**Comment by amarburg** [comment]
That's great, thank you.
