### ISSUE TITLE
Investigate/Design possible new electrical actuator (claw) 

### ISSUE THREAD

**Issue by andrespulido8** [uf-mil/mil#246]
Since the motivation is not to use pneumatic for the new sub. An investigation about new method of manipulation needs to be conducted. Look at past competitions to know what kind of manipulation will probably be needed for future competitions and try to find an existing solution, or design one from scratch. Another good resource is to look for what other teams have approached this problem (find their videos, papers, and websites for more info).
Website: https://robosub.org/programs/2019/.
Contact: Andres Pulido

**Comment by MechAnger** [comment]
Collin Larke is assigned

**Comment by MechAnger** [comment]
Design is done, just needs to be printed
