### ISSUE TITLE
Investigate/Design new electrical ball dropper

### ISSUE THREAD

**Issue by andrespulido8** [uf-mil/mil#247]
Since the motivation is not to use pneumatic for the new sub. An investigation about new ball dropper needs to be conducted. Look for the design of how other teams have approached this problem (find their videos, papers, and websites for more info) , or design one from scratch.
Website: https://robosub.org/programs/2019/.
Contact: Andres Pulido

**Comment by MechAnger** [comment]
Andres Castrillon is assigned

**Comment by andrespulido8** [comment]
Design is done. It just needs to be printed
