### ISSUE TITLE
Investigate/Design a new electrical torpedo launcher

### ISSUE THREAD

**Issue by andrespulido8** [uf-mil/mil#248]
Since the motivation is not to use pneumatic for the new sub. An investigation about new torpedo launcher needs to be conducted. Look for the design of how other teams have approached this problem (find their videos, papers, and websites for more info) , or design one from scratch.
Website: https://robosub.org/programs/2019/.
Contact: Andres Pulido

**Comment by MechAnger** [comment]
Ruben Gonzalez-Vera is assigned

**Comment by andrespulido8** [comment]
@MihirRao01 what is the path to the torpedo design in GrabCAD?

**Comment by MihirRao01** [comment]
I believe it is subjuGator 9 Cad ->Electric Torpedo Launcher @andrespulido8

**Comment by andrespulido8** [comment]
@MihirRao01 mount to the sub appears to be missing in the assembly. Also lets manufacture (print) it before closing for sure

**Comment by MihirRao01** [comment]
@andrespulido8 I closed it because there was another issue open focusing on the torpedo launcher. I wanted to get rid of any duplicates to avoid confusion.

**Comment by MechAnger** [comment]
#351
