### ISSUE TITLE
Design and manufacture wheels for Sub 8

### ISSUE THREAD

**Issue by andrespulido8** [uf-mil/mil#257]
One cool idea we had is to have wheels that could be easily and quickly attached to Emily (Sub 8) in order to transport it more during competition. Wheels need to be big enough to go though roughish terrain. 

Contact: Mikaela De Gracia and Lora Nowicki, they were working on this last semester.

**Comment by andrespulido8** [comment]
@mikaela-dg @MihirRao01 write in here where the files are located and if it is done being built

**Comment by mikaela-dg** [comment]
Files are in the GrabCAD, Subjugator 8 > CAD > wheel project > new frame, Frame is assembled and wheels to be attached
