### ISSUE TITLE
Desing feet for new sub

### ISSUE THREAD

**Issue by MechAnger** [uf-mil/mil#283]
Design new feet for sub, apply stress analysis, research into different materials than ABS if necessary, mounting holes are already made for the feet on the new sub

**Comment by mikaela-dg** [comment]
Contact me on Slack (Mikaela De Gracia) if you are interested. What is left to be done is run FEA on the part and make any final adjustments.

**Comment by MechAnger** [comment]
The design is completed, just needs to be 3-D Printed
