### ISSUE TITLE
Design mount for Hall Effect Sensor 

### ISSUE THREAD

**Issue by andrespulido8** [uf-mil/mil#298]
The hall Effect sensor (a magnet taped into the main vessel frame) that controls the hardware kill needs a 3D printed mount to prevent it from coming loose.

Talk to an electrical to test that mount is working

**Comment by MechAnger** [comment]
Also, design the new kill wand (with a magnet cutout) and a way to permanently mount the kill wand onto the main vessel outside without velcro. PLA and ABS is suggested for simplicity for both.

**Comment by MechAnger** [comment]
![image](https://user-images.githubusercontent.com/60702990/123715714-dfdc5000-d846-11eb-8437-966940613df1.png)

**Comment by MechAnger** [comment]
similar to this where the pvc pipe is currently at on sub 8

**Comment by cbrxyz** [comment]
The Hall Effect Sensor on SubjuGator has now been deprecated in favor of an electrical kill system.
