### ISSUE TITLE
First look at the potential new website from Software Engineering class team 

### ISSUE THREAD

**Issue by kawaiiPlat** [uf-mil/mil#302]
We need to finish the hand over the website project that was developed by Douglas Shu and his group for the Software Engineering class. I will upload the website files to a separate repo or this one as we see fit. We need to determine whether or not we want to use the website stack they used, and if we can easily mantain the website with minimal ongoing effort.

**Comment by MechAnger** [comment]
Website is almost done. Alex Perez made documentation on it which will be uploaded. Maybe for NaviGator update this coming up fall.
