### ISSUE TITLE
Carbon Fiber Tubing and Connectors on Sub 9

### ISSUE THREAD

**Issue by MechAnger** [uf-mil/mil#310]
Website that manufactures carbon tubes and others :https://dragonplate.com/
Website for connectors: https://dragonplate.com/
Scotchweld 2216B (Epoxy): https://www.3m.com/3M/en_US/p/d/b40066427/
Microspheres (choose which type): https://iopscience.iop.org/article/10.1088/1757-899X/205/1/012022/pdf

Count and measure the diameter of the connectors needed, get the CF tube length needed, cut in the house using bandsaw slowly (follow standard procedure for cutting, CF dust is not good for lungs and surround area), add 10% weight in micro-spheres to the epoxy (increases the shear load capabilities of the VF to CF), add marine grade expandable foam, and put them together.

**Comment by castry434** [comment]
Contact Andres Castrillon or Damir on slack for additional documentation related to the carbon tubing
