### ISSUE TITLE
Manufacturing of Sub 9's metal frame

### ISSUE THREAD

**Issue by castry434** [uf-mil/mil#314]
Instructions on how to get started in the process for manufacturing of sub 9's metal frame:

We have to export to DXF files from solidworks. Send those to different companies. Compare prices, then send it to Dr.Schwartz so he can ask how much JD^2 will charge for that (they know Dr.Schwartz and our lab) and then compare how much it'll be in the DML lab with Noel Thomas. As soon as the best price vs best type of work will be figured out, frame can be started.

Contact Andres Castrillon on Slack for additional information.

**Comment by J4mZzy** [comment]
I will be working on this issue
