### ISSUE TITLE
Manufacture shoe box (main PV) for Sub 9

### ISSUE THREAD

**Issue by andrespulido8** [uf-mil/mil#317]
Choose someone to lead the manufacturing efforts of the shoebox. Figure out if it can be made in the lab CNC, with the DML CNC or outsource.

Contact Andres Castrillon on slack if you are interested in this task. Talk to DanP if you want to learn how to use the CNC machine at MIL

**Comment by MihirRao01** [comment]
Designed but not manufactured (JD^2 will manufacture)
