### ISSUE TITLE
Export URDF file for Sub9

### ISSUE THREAD

**Issue by castry434** [uf-mil/mil#319]
The assembly for SubjuGator 9 must be exported as a URDF file so we can give it to the software team. This file is used for the model of the sub in their simulations. In order to export it, you might need to create a simplified version of the assembly that preserves the main parameters of the full assembly (e.g. it's general geometry and weight distribution.)

Contact Andres Castrillon on Slack if you are interested in this task.

**Comment by MechAnger** [comment]
[Sub9.zip](https://github.com/uf-mil/mil/files/7611300/Sub9.zip)

**Comment by MechAnger** [comment]
Sent the complete version of sub 9 to Alex Perez.
