### ISSUE TITLE
Finishing Front Panel for CNC Enclosure

### ISSUE THREAD

**Issue by castry434** [uf-mil/mil#336]
Last semester, I built a new enclosure for the CNC machine made out of 80/20 but the front panel/ door still needs to be added. There are some 80/20 pieces already cut out that can be used or you can cut more using the band saw in the lab. There's also a solidworks model of the enclosure that can be found in GrabCAD that you can edit and reference.

Contact Andres Castrillon if you have any questions.

**Comment by davidreyes2002** [comment]
Worked on a design idea but still need to place 80/20 fasteners, add clear sheets, and door handles

**Comment by MechAnger** [comment]
https://www.omiocnc.com/products/x8-2200epl.html
