### ISSUE TITLE
Add material properties to all components in Sub 9 assembly

### ISSUE THREAD

**Issue by castry434** [uf-mil/mil#337]
Some of the components in the Sub 9 assembly on SolidWorks don't have any material properties assigned to them. Someone has to go through the full assembly and assign the correct material for every component. For example, if a part is going to be 3D printed, you should assign it as PLA or ABS plastic. It's important that all the components have the right materials so that the properties of the overall assembly, like the center of mass, are accurate on SolidWorks.

**Comment by cbrxyz** [comment]
Mechanical issue
