### ISSUE TITLE
VRX: Pose estimation for VRX (combine IMU+GPS)

### ISSUE THREAD

**Issue by kev-the-dev** [uf-mil/mil#34]
VRX gives us an IMU and GPS on ros topics. Use a kalman filter, such as the [robot_localization](http://wiki.ros.org/robot_localization) to output a unified POSE (position + orientation)

**Comment by kev-the-dev** [comment]
Updates? We have a hacked together solution but a custom written kalman filter would be better

**Comment by gavinstjohn** [comment]
No substantial updates, been swamped with schoolwork.

**Comment by kev-the-dev** [comment]
We have a working solution using ROS's `robot_localization` package. I still encourage someone to develop our own as `robot_localization` has some major issues.

I'd be sure our solution at least:

* Uses quaternions rather than euler angles

**Comment by kev-the-dev** [comment]
Our solution using the ROS package is sufficient and I have not heard from the assigned developer, closing
