### ISSUE TITLE
Noetic with Alabaster

### ISSUE THREAD

**Issue by alexperez33** [uf-mil/mil#348]
## Noetic with Alabaster

_For a quick link to the Python 2 → 3 Migration Table, please [click here](https://github.com/uf-mil/mil/issues/348#issuecomment-1016819460)._

The **Noetic with Alabaster** project is a team subproject primarily dedicating to updating all team systems to use ROS Noetic instead of ROS Melodic. Furthermore, the project is also adding extensive documentation on team systems to make it much easier for new and old members to get acquainted with systems they have never touched. This is being done to improve the developer experience and the speed at which projects can be completed.

The project leader is @cbrxyz. The project completion date is scheduled for August 2022, the start of the Fall 2022 semester. At this point, all new and old members will be asked to update their operating system to Ubuntu 20.

If you want to help out, please let the project lead, Cameron, know! She would love to help you get setup!

For more information about the migration, please see some of the links below.

**Links:**
* [Getting Started with Migrating](https://mil.readthedocs.io/en/latest/docs/development/noetic_migration.html)
* [Alabaster Documentation Preview](https://noetic.cbrxyz.com)

**Comment by cbrxyz** [comment]
Just a word of caution about `search`: Powerful tool, but `search .py` will also pick up `.pyc` files, and a few scripts with `py` in their name.

You may want to use `search '^.*\.py$'` instead!

```sh
$ search .py | wc -l
759
$ search '^.*\.py$' | wc -l
580
```

Also, helpful link with info about the differences between Python 2 and 3 to complement the link Alex sent above: https://portingguide.readthedocs.io/en/latest/index.html

**Comment by cbrxyz** [comment]
<h1 align = "center"> 🐍 Python 2 → 3 Migration Plan </h1>

Below is a comprehensive list of packages that need to be migrated from Python 2 to Python 3, separated by system. Issues should be made for each package that needs to be converted, with a reference to such issue here!

To avoid having our inboxes and issue page flooded with new issues, only a few issues relevant to this project will be made at any one time!

### Helpful Tools

Here are a collection of tools that can be used to assist in the migration process:

- [`python-modernize`](https://modernize.readthedocs.io/en/latest/): A command-line tool to check for any Python 2 code which will need to be upgrade to Python 3. After migrating a file, this command should produce no output.

### Navigator (31 packages)
- [ ] `NaviGator/gnc/navigator_msg_multiplexer`
- [ ] `NaviGator/gnc/navigator_thrust_mapper`
- [ ] `NaviGator/gnc/navigator_path_planner`
- [ ] `NaviGator/gnc/navigator_controller`
- [ ] `NaviGator/hardware_drivers/navigator_kill_board`
- [ ] `NaviGator/mission_control/navigator_alarm`
- [ ] `NaviGator/mission_control/navigator_launch`
- [ ] `NaviGator/mission_control/navigator_missions`
- [ ] `NaviGator/mission_systems/navigator_scan_the_code`
- [ ] `NaviGator/perception/navigator_vision`
- [ ] `NaviGator/satellite/rviz_satellite`
- [ ] `NaviGator/simulation/VRX/vrx/usv_gazebo_plugins`
- [ ] `NaviGator/simulation/VRX/vrx/usv_msgs`
- [ ] `NaviGator/simulation/VRX/vrx/vrx_gazebo`
- [ ] `NaviGator/simulation/VRX/vrx/wamv_description`
- [ ] `NaviGator/simulation/VRX/vrx/wamv_gazebo`
- [ ] `NaviGator/simulation/VRX/vrx/wave_gazebo`
- [ ] `NaviGator/simulation/navigator_2dsim`
- [ ] `NaviGator/simulation/navigator_gazebo`
- [ ] `NaviGator/test/navigator_test`
- [ ] `NaviGator/utils/navigator_battery_monitor`
- [ ] `NaviGator/utils/navigator_gui`
- [ ] `NaviGator/utils/navigator_judgepanel`
- [ ] `NaviGator/utils/navigator_judgepanel/src`
- [ ] `NaviGator/utils/navigator_msgs`
- [ ] `NaviGator/utils/navigator_robotx_comms`
- [ ] `NaviGator/utils/navigator_tools`
- [ ] `NaviGator/utils/remote_control/navigator_emergency_control`
- [ ] `NaviGator/utils/remote_control/navigator_joystick_control`
- [ ] `NaviGator/utils/remote_control/navigator_keyboard_control`
- [ ] `NaviGator/utils/voltage_gui`

### Subjugator (? packages)

These packages will be listed soon, as more of the `NaviGator` packages are completed.

### `mil_common` (? packages)

These packages will be listed soon, as more of the `NaviGator` packages are completed.

**Comment by cbrxyz** [comment]
This issue is finally closed. Thank you to all who helped out with this project, we could not have done it without you.
