### ISSUE TITLE
Create bill of materials for sub 9 and see what still needs to be order

### ISSUE THREAD

**Issue by castry434** [uf-mil/mil#352]
Go through the assembly for sub 9 and create a bill of materials for all the components that are necessary to assemble sub 9 (Only focus on mechanical components; don't take into account the electronics)
All these components should be added to a spreadsheet where they can be listed. Create a column next to this list where, next to each component you mark it with one of the following labels: "In lab and ready for assembly", "Needs to be manufactured", "Needs to be ordered"

This task will help us make sure we have everything ready to put sub 9 together.

Contact Andres Castrillon on Slack if you have any questions.

**Comment by cbrxyz** [comment]
mech issue :3
