### ISSUE TITLE
Investigation of Scan and Dock Task

### ISSUE THREAD

**Issue by alexperez33** [uf-mil/mil#371]
Task six requires the boat to detect patterns of shapes and dock in a certain area depending on the pattern. Luckily for us, this is very similar to task six of the previous competition. Read through ```scan_and_dock.py``` and ```scan_the_code.py``` in the ```navigator_missions``` package, and report back what the old strategy was and what we can potentially use from it. Also think about how we can potentially improve it.

Here are the previous competitions task descriptions:
https://robonation.org/app/uploads/sites/2/2019/09/VRX2019_Task-Descriptions_v1.2.pdf

Here is the new task description:
https://robonation.org/app/uploads/sites/2/2021/09/VirtualRobotX2022_Task-Descriptions_v1.0.pdf

**Comment by m-heck** [comment]
Brief google doc about the task:
https://docs.google.com/document/d/1d9FOZQpgDcI0LlNnSeZarNBHGTxKVQS2F3L5W5xBa8c/edit?usp=sharing
