### ISSUE TITLE
Point Grey Camera Investigation

### ISSUE THREAD

**Issue by alexperez33** [uf-mil/mil#379]
Look into the Point Grey Camera, determine how it was used in our code, determine if it is still applicable and/or if we can make improvements to our processing of the point grey camera data.

How to potentially get started:
- look at camera on sub
- try to determine type of camera and find documentation on it online
- maybe you can find hints in the repository using "grep -r"
- check out ```pointgrey_camera_driver``` package in the repository

**Comment by Abishanka** [comment]
/*
   Issue solved by doing online research. Summary enclosed below.
*/

Basic Information Data Found in: https://github.com/uf-mil/mil/blob/master/deprecated/wikis/SubjuGator/Cameras.md

SubjuGator 8's visual stack will contain three cameras. They are the following:

Stereo System: Two Point Grey Chameleon3s (CM3-13S2C)
Downward System: One Point Grey Blackfly (U3-13S2C)

FOV of 140degree (Omnidirectional)
	Possible reason for using???
-------------------------------------------------------------------------------

Camera GUIDs:

Left Stereo: 00b09d0100ea51c4
Right Stereo: 00b09d0100ea51be
Downward: 00b09d0100eabf6c

-------------------------------------------------------------------------------

PointGrey Camera used in file:
	https://github.com/uf-mil/mil/blob/master/SubjuGator/command/sub8_launch/launch/subsystems/cameras/launch/right_camera.launch

Right camera is using camera with GUID: 00b09d0100ea51c4
Deprecated doc mentions it being used as Left Camera

According to 
	https://github.com/uf-mil/mil/blob/master/SubjuGator/command/sub8_launch/launch/subsystems/cameras/calibration/front_right_cam.yaml
Camera outputs: image_width: 644
				image_height: 482

Possibly try changeing it to have a better resolution???

Inferior to other cameras giving 1920 x 1080

-------------------------------------------------------------------------------

Product page: https://www.flir.com/products/chameleon3-usb3/?model=CM3-U3-13S2C-CS-BD&vertical=machine-vision&segment=iis
