### ISSUE TITLE
Migrate the `NaviGator/gnc/navigator_thrust_mapper` package from Python 2 to Python 3

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#390]
The `NaviGator/gnc/navigator_thrust_mapper` package should be migrated from Python 2 to Python 3.

For more information, please see [this issue comment](https://github.com/uf-mil/mil/issues/348#issuecomment-1016819460).

**Comment by Krish-bhardwaj** [comment]
Hi i am a fresher looking for some opensource contribution can u help me out i want to contribute to your project and can u assign me this project :)
