### ISSUE TITLE
Freeze pip packages in Noetic setup scripts

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#415]
To hopefully prevent dependency conflicts, the `pip` packages installed in the Noetic setups scripts should have their versions frozen.

To complete this task, install the latest Python 3 packages through `pip3`. Then, run `pip3 freeze` and save the noted versions into the setup scripts.

**Comment by RishiKumarRay** [comment]
do we need to create  file named setup scripts

**Comment by cbrxyz** [comment]
Closed in the Noetic + Alabaster project. Pip dependencies are now managed through `requirements.txt` and `requirements_test.txt`.
