### ISSUE TITLE
Migrate the `NaviGator/utils/remote_control/navigator_keyboard_control` package from Python 2 to Python 3

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#434]
The `NaviGator/utils/remote_control/navigator_keyboard_control` package should be migrated from Python 2 to Python 3.

For more information, please see [this issue comment](https://github.com/uf-mil/mil/issues/348#issuecomment-1016819460).

**Comment by dpearson2699** [comment]
Merged in #456
