### ISSUE TITLE
Improve clustering algorithm of PCODAR

### ISSUE THREAD

**Issue by alexperez33** [uf-mil/mil#474]
The idea for this issue is to improve the clustering algorithm so that we can better differentiate buoys that are close together without breaking up a large object into multiple clusters. We have to find a way to balance this.

To run the perception task normally, you can run ```roslaunch navigator_launch vrx.launch run_task:=True world:=perception_task --screen```

There are several ways we can go about this. One is adjusting the parameters that control how the pcodar behaves. Another is looking into the pcodar code and adjusting the actual lidar code is processed. This will require investigation.

If you have any questions, please contact Alex Perez.

**Comment by cbrxyz** [comment]
There's not much more to do on this for right now. Let's focus our time and energy into other places.
