### ISSUE TITLE
Get more buoy data that we can use for our YOLO model

### ISSUE THREAD

**Issue by alexperez33** [uf-mil/mil#476]
Like any ML model, the more data the better. We want to obtain camera data of buoys in various environments so that our YOLO model can be more versatile in being able to detect where these objects are during competition.

How can we get more data?
First we have to define what type of data we want to collect. These are the variables we can change when making our dataset:

- distance from buoy
- type of buoy
- size of waves
- ambient lighting
- fog
- wind

We already have a lot of data from the world files within ```mil/NaviGator/simulation/VRX/vrx/vrx_gazebo/worlds```. Other tasks are on the way to develop more complicated perception and gymkhana tasks. Once those are available we will need to run the task within that world and run:

```rosbag record -O name_of_bag.bag /wamv/sensors/cameras/front_left_camera_image_raw```

To view the recorded camera data:
In one terminal: run ```roscore```
In a second terminal: run ```rqt```
Open the image view plugin.
In a third terminal: run ```rosbag run name_of_bag.bag```.

Once you have the bags you want to get the images from, contact Alex Perez, and we can upload the images from that bag into Labelbox.

**Comment by Enemias-Itzep** [comment]
rosbag record -O name_of_bag.bag /wamv/sensors/cameras/front_left_camera/image_raw
