### ISSUE TITLE
Add textures to RoboSub 2022 gazebo models

### ISSUE THREAD

**Issue by alexperez33** [uf-mil/mil#594]
**This task is related to the 2022 RoboSub competition. Interested in helping out? Please click here to navigate to the [parent issue](https://github.com/uf-mil/mil/issues/608) or the [parent project](https://github.com/uf-mil/mil/projects/7), which can show you how to get started.**

The gazebo models we use to create our simulated worlds don't export textures. So we have to manually add the textures to the models after they have been exported. 

In the past, previous software members have done this and it has been documented in the README.md file within the sub8_gazebo package. Look in this file and investigate if this is still possible so we can recreate more accurate simulated worlds.

Ideally, this would be done by the end of May or early June (assuming it is possible).

The elements that need texturing are:
- [ ] The start gate
- [ ] The pick your side bouys
- [ ] The Path Markers
- [ ] ...

EDIT: Extra information
Here is a link to a README on how previous software members have added textures in the past:
https://github.com/uf-mil/mil/blob/master/SubjuGator/simulation/sub8_gazebo/README.md
 You should be able to view the dae file created through this website, which should reflect what will show up in Gazebo:
https://www.creators3d.com/online-viewer

**Comment by kawaiiPlat** [comment]
Task sidelined due to availability and consultation with previous SW team members. Closing
