### ISSUE TITLE
Get active sonar working (if possible)

### ISSUE THREAD

**Issue by alexperez33** [uf-mil/mil#598]
We will be able to have an active sonar under three conditions:
- We figure out a way to replace the wires and connectors needed for our active sonar to work
- We purchase a new active sonar and it comes in soon
- We find the old active sonar cable and purchase a replacement connector.

Once we get the hardware, we would need to be able to integrate the sensor data coming in. We need to look into each of these possibilities pursue them if possible, and once one of the avenues seem likely, begin determine how we integrate the sensor data.

**Comment by cbrxyz** [comment]
We are foregoing this task for this competition. 🏳
