### ISSUE TITLE
Investigate a better kill system

### ISSUE THREAD

**Issue by alexperez33** [uf-mil/mil#603]
Currently for SubjuGator, we have a kill system that we have always had trouble with. In theory, it should be reliable, however, it simple has not been in my experience.

The purpose of the kill system is to stop all power the thrusters if anything goes wrong. There are several options to create a better kill system. Perhaps we could place stronger magnets in the PVC pipe, perhaps we can create a stronger mount for the PVC pipe, or perhaps we can desert the whole magnet/hall effect sensor altogether in favor of some sort of wireless signal that can penetrate the water and hull of the sub. Or maybe there can be a physical button on the sub.

Regardless, we need a working kill system for Sub8 whatever it may be. And the kill system that looks the most promising can be implemented into Sub9.

**Comment by cbrxyz** [comment]
This was completed by @mehront and @aramesh10 at the 2022 RoboSub competition. The kill system was modified from a physical mount stick to an electric kill triggered by the flick of a switch on a cord attached to the sub.

No changes were made software-wise to facilitate this change.
