### ISSUE TITLE
Docs: Dead link to old development guide.

### ISSUE THREAD

**Issue by kawaiiPlat** [uf-mil/mil#620]
The main [SubjuGator](https://mil.readthedocs.io/en/latest/docs/subjugator/index.html) page in the docs has a link to the (now deprecated) [Development Guide](https://mil.readthedocs.io/en/latest/docs/development/development_guide.html), this should probably point to [Getting Started](https://mil.readthedocs.io/en/latest/docs/development/getting_started.html) instead.

[This](https://mil.readthedocs.io/en/latest/docs/development/adding_documentation.html) gives a guide on how to work with the documentation.

**Comment by cbrxyz** [comment]
This also needs to be fixed in Alabaster! Thanks for catching this Jarrod! 👍

**Comment by cbrxyz** [comment]
This has been fixed. Thanks Jarrod!
