### ISSUE TITLE
Develop OpenCV algorithm for recognizing the RoboSub 2022 start gate

### ISSUE THREAD

**Issue by alexperez33** [uf-mil/mil#661]
**This task is related to the 2022 RoboSub competition. Interested in helping out? Please click here to navigate to the [parent issue](https://github.com/uf-mil/mil/issues/608) or the [parent project](https://github.com/uf-mil/mil/projects/7), which can show you how to get started.**

We need to be able to find the start gate at the beginning of the mission. Look into using OpenCV to be able to detect the start gate and accurately travel towards it.

@andrew-aj, in terms of data you can test with, there are the images I sent you related to the real life data from testing. There is a branch called sub8_testing_2022 branch which contains the old start gate. And very soon, in master, we will have the correct start gate in simulation.

This task can be marked as complete when a vision algorithm generally works for a variety of environmental conditions, and a leader has approved on the implementation of the algorithm. Because this algorithm will be implemented via Python or C++ code, this issue will probably be closed in a PR.

**Comment by kawaiiPlat** [comment]
Switched to yolo during the event, closing.
