### ISSUE TITLE
Develop OpenCV algorithm for finding orange path markers

### ISSUE THREAD

**Issue by alexperez33** [uf-mil/mil#662]
**This task is related to the 2022 RoboSub competition. Interested in helping out? Please click here to navigate to the [parent issue](https://github.com/uf-mil/mil/issues/608) or the [parent project](https://github.com/uf-mil/mil/projects/7), which can show you how to get started.**

For this task, you will need to construct an OpenCV pipeline that can take in an image from the sub's down cam and return the trajectory that the sub needs to travel to to hit the next task.

In order to get started, you will likely want to check out the `sub8_testing_2022` branch. This has some models in a world we have been developing thus far. By launching ```roslaunch sub8_launch gazebo.launch```, you can launch the simulation of the sub. By then running ```gazebogui``` or ```rqt```, you should be able to see the models. (Note if you use rqt, you will have to open the camera plugins to see what the sub is seeing.)

It would be wise to take images from rqt that you can use to develop your opencv code (when moving the sub over the path markers). This will allow quicker development. Feel free to move the path markers anywhere in the gazebo world for developmental purposes.

This issue can be completed when the vision algorithm works in a variety of environments and a leader has agreed to implement the algorithm. Closing this issue will require code, and therefore, this issue should likely be closed in a PR.

**Comment by cbrxyz** [comment]
I'm interested in taking up this task. I'm going to start looking into how to at least find the general shape/color range of the path marker, without worrying about the possible effects of the light/pool/environment! I'll update when I have more information.

**Comment by kawaiiPlat** [comment]
Nature of the event makes marker finding unnecessary, closing.
