### ISSUE TITLE
MRAC Controller update

### ISSUE THREAD

**Issue by MarshallRawson** [uf-mil/mil#67]
MRAC controller currently has hard coded values for WAMV mass/inertia and gains. These should be read from the urdf / passed by a launch file respectively.  Also MRAC has a thrust mapper that is no used. It should be deprecated.

**Comment by kev-the-dev** [comment]
Partially complete on this. Gains and mass/inertial is read from launch file. There are documented reasons to have the controller's model of mass be different from the simulators (related to water mass?).

The thruster mapping lines should still be removed.
