### ISSUE TITLE
Construct a physical start gate for the 2022 RoboSub competition

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#680]
**This task is related to the 2022 RoboSub competition. Interested in helping out? Please click here to navigate to the [parent issue](https://github.com/uf-mil/mil/issues/608) or the [parent project](https://github.com/uf-mil/mil/projects/7), which can show you how to get started.**

This task requires the construction of a physical start gate for the 2022 RoboSub competition. The dimensions of the start gate and the materials used to make the start gate can be found on page 12 of the RoboSub 2022 rules manual (a link to the manual can be found on the parent issue linked above).

To complete, the task, construct a physical start gate that meets the appropriate requirements. You do not need to add any code to complete this issue.

For notes on where to find materials/how to proceed with the construction of the physical object, please see the [Manufacturing header in the parent issue](https://github.com/uf-mil/mil/issues/608#user-content-manufacturing) linked at the top of this issue.

A quick view of the start gate requirements can be seen below:
![ss 2022-06-11 at 21 25 54](https://user-images.githubusercontent.com/52760912/173210375-72d62208-8a37-4968-af55-51a4d6c7dcf8.png)

**Comment by cbrxyz** [comment]
Currently, the physical start gate is not the appropriate color. That is all that should need to be fixed for this task to be marked as complete, for all that I am aware.

**Comment by mitchellrobert** [comment]
Unless someone else made another start gate, the one we have is only 1in pvc while we need a gate that is 3in pvc

**Comment by kawaiiPlat** [comment]
Start gate was assembled, closing
