### ISSUE TITLE
Construct a physical path marker for the 2022 RoboSub competition

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#681]
**This task is related to the 2022 RoboSub competition. Interested in helping out? Please click here to navigate to the [parent issue](https://github.com/uf-mil/mil/issues/608) or the [parent project](https://github.com/uf-mil/mil/projects/7), which can show you how to get started.**

This task requires the construction of a physical path marker for the 2022 RoboSub competition. The dimensions of the path marker and the materials used to make the path marker can be found on page 13 of the RoboSub 2022 rules manual (a link to the manual can be found on the parent issue linked above).

To complete, the task, construct a physical start gate that meets the appropriate requirements. You do not need to add any code to complete this issue.

For notes on where to find materials/how to proceed with the construction of the physical object, please see the Manufacturing header in the parent issue linked at the top of this issue.

A quick view of the path marker requirements can be seen below:
![ss 2022-06-11 at 21 33 15](https://user-images.githubusercontent.com/52760912/173210445-1b9d78ff-9bdc-4fb6-9bdd-3d6fda66ae34.png)

**Comment by kawaiiPlat** [comment]
Path markers were constructed, closing
