### ISSUE TITLE
Construct two physical Make the Grade buoys for the 2022 RoboSub competition

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#682]
**This task is related to the 2022 RoboSub competition. Interested in helping out? Please click here to navigate to the [parent issue](https://github.com/uf-mil/mil/issues/608) or the [parent project](https://github.com/uf-mil/mil/projects/7), which can show you how to get started.**

This task requires the construction of the physical Make the Grade buoys for the 2022 RoboSub competition. The dimensions of the buoys and the materials used to make the buoys can be found on page 14 of the RoboSub 2022 rules manual (a link to the manual can be found on the parent issue linked above).

For notes on where to find materials/how to proceed with the construction of the physical object, please see the [Manufacturing header in the parent issue](https://github.com/uf-mil/mil/issues/608#user-content-manufacturing) linked at the top of this issue.

To complete, the task, construct two physical buoys that meet the appropriate requirements. You do not need to add any code to complete this issue.

A quick view of the Make the Grade buoys can be seen below:
![ss 2022-06-11 at 21 35 00](https://user-images.githubusercontent.com/52760912/173210480-ae04866b-3c1f-425d-892a-28c0caa41106.png)

**Comment by cbrxyz** [comment]
We have the image of the badge, but are still missing the image of the gun.

**Comment by kawaiiPlat** [comment]
Bouys were assembled, closing
