### ISSUE TITLE
Construct the physical bin environment for the 2022 RoboSub competition

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#683]
**This task is related to the 2022 RoboSub competition. Interested in helping out? Please click here to navigate to the [parent issue](https://github.com/uf-mil/mil/issues/608) or the [parent project](https://github.com/uf-mil/mil/projects/7), which can show you how to get started.**

This task requires the construction of a physical bin environment for the 2022 RoboSub competition. This environment includes a few related pieces:
- [ ] Bin frame
- [ ] Bootlegger Image
- [ ] G-Man Image
- [ ] Cover for bin

The dimensions of the pieces and the materials used to make each piece can be found on page 15 of the RoboSub 2022 rules manual (a link to the manual can be found on the parent issue linked above).

To complete, the task, construct a physical start gate that meets the appropriate requirements. You do not need to add any code to complete this issue.

For notes on where to find materials/how to proceed with the construction of the physical object, please see the [Manufacturing header in the parent issue](https://github.com/uf-mil/mil/issues/608#user-content-manufacturing) linked at the top of this issue.

A quick view of the bin environment requirements can be seen below:
![ss 2022-06-11 at 21 39 20](https://user-images.githubusercontent.com/52760912/173210570-024a4591-ba02-4541-9150-1d2fdc052804.png)

**Comment by kawaiiPlat** [comment]
Bins were assembled, closing
