### ISSUE TITLE
Construct physical Survive the Shootout buoys for the 2022 RoboSub competition

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#684]
**This task is related to the 2022 RoboSub competition. Interested in helping out? Please click here to navigate to the [parent issue](https://github.com/uf-mil/mil/issues/608) or the [parent project](https://github.com/uf-mil/mil/projects/7), which can show you how to get started.**

This task requires the construction of a physical start gate for the 2022 RoboSub competition. The dimensions of the buoys and the materials used to make the buoys can be found on page 16 of the RoboSub 2022 rules manual (a link to the manual can be found on the parent issue linked above).

To complete, the task, construct the buoys which meet the appropriate requirements. You do not need to add any code to complete this issue.

For notes on where to find materials/how to proceed with the construction of the physical object, please see the [Manufacturing header in the parent issue](https://github.com/uf-mil/mil/issues/608#user-content-manufacturing) linked at the top of this issue.

A quick view of the buoy requirements can be seen below:
![ss 2022-06-11 at 21 41 18](https://user-images.githubusercontent.com/52760912/173210608-c8f0bb57-f880-4362-b017-48d8d681fa16.png)

**Comment by kawaiiPlat** [comment]
Bouys were assembled, closing
