### ISSUE TITLE
Construct a physical surfacing octagon for the 2022 RoboSub competition

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#685]
**This task is related to the 2022 RoboSub competition. Interested in helping out? Please click here to navigate to the [parent issue](https://github.com/uf-mil/mil/issues/608) or the [parent project](https://github.com/uf-mil/mil/projects/7), which can show you how to get started.**

This task requires the construction of a physical octagon for the 2022 RoboSub competition. The dimensions of the octagon and the materials used to make the octagon can be found on page 17 of the RoboSub 2022 rules manual (a link to the manual can be found on the parent issue linked above).

To complete, the task, construct a physical octagon that meets the appropriate requirements. You do not need to add any code to complete this issue.

For notes on where to find materials/how to proceed with the construction of the physical object, please see the [Manufacturing header in the parent issue](https://github.com/uf-mil/mil/issues/608#user-content-manufacturing) linked at the top of this issue.

A quick view of the octagon requirements can be seen below:
![ss 2022-06-11 at 21 42 49](https://user-images.githubusercontent.com/52760912/173210653-53335d2a-7e02-4f49-a798-990d60e4702a.png)

**Comment by kawaiiPlat** [comment]
Octagon was assembled, closing
