### ISSUE TITLE
Construct physical bottle tables for the 2022 RoboSub competition

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#686]
**This task is related to the 2022 RoboSub competition. Interested in helping out? Please click here to navigate to the [parent issue](https://github.com/uf-mil/mil/issues/608) or the [parent project](https://github.com/uf-mil/mil/projects/7), which can show you how to get started.**

This task requires the construction of three physical bottle tables for the 2022 RoboSub competition. The dimensions of the tables and the materials used to make each table can be found on page 17 of the RoboSub 2022 rules manual (a link to the manual can be found on the parent issue linked above).

To complete, the task, construct three physical tables that meets the appropriate requirements. You do not need to add any code to complete this issue.

There should be three tables, one for:
- [ ] The G-Man mission
- [ ] The Bootlegger mission
- [ ] The bottle table, where all bottles are initially placed

For notes on where to find materials/how to proceed with the construction of the physical object, please see the [Manufacturing header in the parent issue](https://github.com/uf-mil/mil/issues/608#user-content-manufacturing) linked at the top of this issue.

A quick view of the start gate requirements can be seen below:
![ss 2022-06-11 at 21 42 49](https://user-images.githubusercontent.com/52760912/173210683-e11cda0b-b0db-4d69-95e0-1486f0dbd761.png)

**Comment by kawaiiPlat** [comment]
Tables were assembled, closing
