### ISSUE TITLE
Develop OpenCV algorithm for detecting Make the Grade buoys

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#695]
**This task is related to the 2022 RoboSub competition. Interested in helping out? Please click here to navigate to the [parent issue](https://github.com/uf-mil/mil/issues/608) or the [parent project](https://github.com/uf-mil/mil/projects/7), which can show you how to get started.**

For this task, you will need to detect an OpenCV algorithm for detecting the differences between the two Make the Grade buoys. For this task, the sub only needs to distinguish the two buoys, so the vision algorithm does not need to be ultra precise. However, it should have good accuracy at determining the differences between the two buoys when placed side-by-side.

To complete this task, develop a vision algorithm that can reliably determine the differences between the two textured buoys when placed side-by-side. The algorithm should not be hindered by environmental variables. Completing this task will likely involve code, therefore, this issue will likely be closed in a PR.

**Comment by kawaiiPlat** [comment]
switched to using yolo during the event, closing.
