### ISSUE TITLE
Develop vision pipeline for recognizing RoboSub 2022 bottles

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#709]
**This task is related to the 2022 RoboSub competition. Interested in helping out? Please click here to navigate to the [parent issue](https://github.com/uf-mil/mil/issues/608) or the [parent project](https://github.com/uf-mil/mil/projects/7), which can show you how to get started.**

For the Cash or Smash mission in the RoboSub 2022 tournament, our submarine needs to be able to recognize plastic bottles laying on a platform. These bottles can be lying flat, or standing up. They are weighed down by the weight of water surrounding them.

This task does not mention "OpenCV" or "machine learning," because these methods will need to be evaluated to see which works better for this specific task. Recognizing bottles in a variety of layouts may be too complicated for OpenCV, but this has not been tested. In this case, machine learning might work better as an approach for recognizing these objects.

The vision pipeline will need to tell the bot where the bottles are, and ideally, how to pick them up (if they are laying, they may need to be picked up differently than if they were standing upright).

To complete this issue, please develop a ROS-compatible vision pipeline for recognizing the bottles. This is understandably a very big task, so it may not just be closed after a few commits. Please verify that the pipeline is appropriate with the software leaders.

References:
* [Plastic Bottle Dimensions Reference](https://smile.amazon.com/Empty-Juice-Bottles-Disposable-Containers/dp/B07DH91CM8/)

**Comment by kawaiiPlat** [comment]
lol no, closing
