### ISSUE TITLE
Develop OpenCV algorithm for identifying openings in RoboSub 2022 Survive the Shootout task

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#710]
**This task is related to the 2022 RoboSub competition. Interested in helping out? Please click here to navigate to the [parent issue](https://github.com/uf-mil/mil/issues/608) or the [parent project](https://github.com/uf-mil/mil/projects/7), which can show you how to get started.**

This task requires the development of an OpenCV algorithm capable of detecting various openings in two underwater buoys. These openings are found so that the submarine can shoot torpedos through them. There are two openings per buoys (an easier opening and a harder opening). The sub should find at least the harder opening in each buoy with relative accuracy - finding the easier buoy is optional.

These openings are marked by red outlines in the images on the buoys (see the image below for an example of this).

To close this issue, develop an OpenCV pipeline that can see the buoys and find the red openings. The pipeline should be able to tell the submarine how to move to the openings. This contribution will likely be code-based, and therefore this issue should be closed in association with one or more PRs.

<img width="300" alt="ss 2022-06-17 at 11 45 22@2x" src="https://user-images.githubusercontent.com/52760912/174341563-a42e93f8-4642-452c-8834-c0703d1308d6.png">

**Comment by kawaiiPlat** [comment]
lol no, closing
