### ISSUE TITLE
Develop OpenCV algorithm for finding marker dropping location for RoboSub 2022 Collecting task

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#711]
**This task is related to the 2022 RoboSub competition. Interested in helping out? Please click here to navigate to the [parent issue](https://github.com/uf-mil/mil/issues/608) or the [parent project](https://github.com/uf-mil/mil/projects/7), which can show you how to get started.**

This task requires the development of an OpenCV vision algorithm that can find the appropriate bin that the sub needs to drop markers into. There are two bins in the course, one for the "good guys" and one for the "bad guys" - the difference between two is in the image placed in each bin. Furthermore, each bin is covered 1/3 of the way by a lid. For an example of what the bins look like, see the image below.

For this task, you will need to develop an OpenCV algorithm that can tell the difference between the two bins, even if 1/3 of the bin is covered.

To close this task, please submit a PR (or multiple) that successfully implement an OpenCV image detection algorithm.

<img width="300" alt="ss 2022-06-17 at 12 13 42@2x" src="https://user-images.githubusercontent.com/52760912/174346414-3d0b4f88-231c-4048-9f7a-11c9b1e34962.png">

**Comment by kawaiiPlat** [comment]
Switched to YOLO model for other vision. closing.
