### ISSUE TITLE
Develop static arm to add to SubjuGator for the RoboSub 2022 Collecting task

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#712]
**This task is related to the 2022 RoboSub competition. Interested in helping out? Please click here to navigate to the [parent issue](https://github.com/uf-mil/mil/issues/608) or the [parent project](https://github.com/uf-mil/mil/projects/7), which can show you how to get started.**

For the RoboSub 2022 Collecting task, we will need to develop a stationery arm capable of removing the top lid from the appropriate bin. This can be done by having the arm "scoop up" the lid off of the bin. In more technical terms, the sub would likely navigate to a point where its arm is under the lid of the bin and then move away from the bin. This would emulate lifting the lid off of the bin.

This arm will need to be designed and added to the sub, and then tested. Furthermore, there may be a desire to have this simulated into our Gazebo simulation, but this has yet to be discussed. The dimensions of the arm are added below.

To close this issue, please design and create an arm that can be added under the sub. This arm should be tested to ensure that it can be used to lift the lid used in the competition.

<img width="300" alt="ss 2022-06-17 at 12 13 42@2x" src="https://user-images.githubusercontent.com/52760912/174347563-099ff9e3-e6a8-41dc-bf86-ce9d627a5a25.png">

**Comment by kawaiiPlat** [comment]
This task was passed over due to lack of availability in 2022. Closing.
