### ISSUE TITLE
Develop OpenCV algorithm to distinguish between bottle tables in RoboSub 2022 Cash or Smash

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#713]
**This task is related to the 2022 RoboSub competition. Interested in helping out? Please click here to navigate to the [parent issue](https://github.com/uf-mil/mil/issues/608) or the [parent project](https://github.com/uf-mil/mil/projects/7), which can show you how to get started.**

For this task of the competition, there are three tables. One of the tables starts with all of the bottles, one of the tables is empty with a large green dollar sign (the "bootlegger" table), and one of the tables has a large axe on it (the "G-Man" table). The bot should be able to distinguish between all three tables (so that it can move between them and place bottles in the appropriate position).

To start, consider making an OpenCV algorithm that can tell the difference between two flat, static images. Then continue developing the algorithm by allowing the algorithm to consider surfaces at an angle.

To complete this task, please contribute a PR (or multiple PRs) that solve this issue. They should be able to distinguish between the tables with a relative amount of accuracy.

<img alt="ss 2022-06-17 at 12 34 49@2x" src="https://user-images.githubusercontent.com/52760912/174349608-dd057a81-44b9-4b30-a9fc-baee1224f951.png">

**Comment by kawaiiPlat** [comment]
Other vision systems used YOLO, closing.
