### ISSUE TITLE
External monitor for sub8/9 electrical system status

### ISSUE THREAD

**Issue by kawaiiPlat** [uf-mil/mil#772]
This is an idea that we had during robosub 2022. The general goal would be to have a quick, waterproof monitoring unit that could be attached to one of the unused ports on the back of sub8, and added to sub 9 if possible. The monitoring system could then display the status of all of the electrical systems as a quick means of evaluating which systems are responsible for issues. This may not be important enough to merit a major, focused effort.

This could be as simple as an LED for each board, or as complex as a full gui with data eveluation readouts and the like. This data should be displayed whether the computer is on or not, and should allow us to know when the electrical hardware and the software don't agree (example being when we didn't have a solid connection to the kill board and saw the sub as killed or unkilled while the hardware kill was still activated.

**Comment by cbrxyz** [comment]
Electrical task
