### ISSUE TITLE
Trim trees around backside of CIMAR

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#812]
**This task is a part of the RobotX 2022 project. For more information on this project, please see [the project page](https://github.com/orgs/uf-mil/projects/3).**
<hr>

For this task, we will need to contact a facilities supervisor in order to have them help us trim some trees near the backside of CIMAR. Without this, we may experience trouble as we try to back the trailer out CIMAR.

We should try to do this sooner rather than later to ensure that there are facilities people able to help us out!

**Comment by kawaiiPlat** [comment]
Trees are trimmed baby, thanks @ems37uf !
