### ISSUE TITLE
Re-examine mission code for Task 6: Detect and Dock

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#820]
**This task is a part of the RobotX 2022 project. For more information on this project, please see [the project page](https://github.com/orgs/uf-mil/projects/3).**
<hr>

This issue can be closed when we re-examine the mission code for Task 6: Detect and Dock to determine what changes need to be made.

This issue may require code changes, in which case a linked PR can be made.

**Comment by cbrxyz** [comment]
The milestone for this task has been updated to **Sunday, 9/25** (2 days from now).

**Comment by andrew-aj** [comment]
Currently working in `docking_vrx` branch so I can test code in the simulation.

**Comment by cbrxyz** [comment]
Thank you Andrew
