### ISSUE TITLE
Design and assemble the docking bay for testing

### ISSUE THREAD

**Issue by castry434** [uf-mil/mil#855]
This is the task we need to build: 
![task](https://user-images.githubusercontent.com/21318718/187259684-ba9e4767-a59c-4c58-afb4-961955cb25b0.JPG)

I think we can use a f[loating boat matt](https://www.google.com/search?q=floating+matt+boat&rlz=1C1RXQR_enUS958US958&hl=en&tbm=isch&sxsrf=ALiCzsY8AuYc7wgIF_TXKbvD24vTTt0smg:1661792762926&source=lnms&sa=X&ved=0ahUKEwjGm8u6xOz5AhX7fTABHRU5BRQQ_AUI2AgoAQ&biw=1334&bih=785&dpr=2.25) to make the platform. 

For the structure holding the colored squares, I recommend building hurdles out of pvc pipe and pasting a poster with a white background and a colored square on each one.

**Comment by MattRPoole** [comment]
Robert, Adam, and Mike
