### ISSUE TITLE
Fix `TF_REPEATED_DATA` warning in Noetic

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#889]
### What needs to change?

With the migration to ROS Noetic, another warning was added to ROS to warn about repeated data being sent in TF. This is different than Melodic, which never warned about this. It's common to see this warning spammed throughout the console of ROS:
```
Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame example/topic/name/goes/here at time 44.470000 according to authority unknown_publisher
         at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.5/src/buffer_core.cpp
```

More information on the actual issue can be found in ros/geometry2#467.

Nevertheless, we would really like to get rid of this warning, as the amount of spam it generates prevents us from seeing actually important warnings and errors. There are a few ways we could go about this, including:
1. Fixing the root issue (ie, preventing transform publishers from sending repeated data).
2. Ignoring the warning or silencing it.
3. Doing a combination of both.

### How would this task be tested?

1. Launch one of our commonly used launch files, such as `roslaunch navigator_launch simulation.launch --screen`.
2. Observe that the `TF_REPEATED_DATA` warning does not appear in the console.

### Contacts

- [ ] We need help from the mechanical team.
- [ ] We need help from the electrical team.
- [ ] We need help from Dr. Schwartz or other faculty.
- [ ] We need help from a company or an organization.
- [ ] We need help from another UF staff member or organization (ex, facilities).

**Comment by yomole** [comment]
Note that, while not a perfect solution, the following can supress the warning most of the time with occasional small flare-ups from time to time:

`roslaunch subjugator_launch gazebo.launch --screen 2> >(grep -Ev 'TF_REPEATED_DATA|buffer_core.cpp | grep -v '^$')`
