### ISSUE TITLE
`mil` Unified Command Project

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#907]
<h1 align="center"><code>mil</code> Unified Command Project</h1>

The `mil` unified command project is a project to unite the various aliases and commands used commonly by MILers to perform actions. Currently, these commands and aliases are scattered throughout the repository, which sets up a challenge for old and new members looking to complete software tasks. Furthermore, documentation can be hard to find or nonexistent for these commands, which provides an even greater barrier to entry.

To solve this, we are starting this project, which will aim to unite all of our commands into one program: `mil`. For example:
* `nmove` (move NaviGator in a direction) → `mil nav move`
* `subviz` (open SubjuGator Rviz config) → `mil sub rviz`
* `list_mil_devices` (list all devices on MIL's network) → `mil network listdevices`

Furthermore, members will be able to run `--help` on the `mil` command to find out more about what the command (and each sub command) does:
```bash
$ mil --help
                                                                                      
 Usage: mil [OPTIONS] COMMAND [ARGS]...                                               
                                                                                      
╭─ Options ──────────────────────────────────────────────────────────────────────────╮
│ --help      Show this message and exit.                                            │
╰────────────────────────────────────────────────────────────────────────────────────╯
╭─ Commands ─────────────────────────────────────────────────────────────────────────╮
│ bag         Manage reading of rosbag files                                         │
│ docs        Manage building of MIL documentation                                   │
│ mission     Run and manage available missions for a robotic system                 │
│ nav         Manage a running instance of NaviGator                                 │
│ network     Manage the local MIL network                                           │
╰────────────────────────────────────────────────────────────────────────────────────╯

$ mil nav --help
                                                                                      
 Usage: mil nav [OPTIONS] COMMAND [ARGS]...                                           
                                                                                      
 Manage a running instance of NaviGator                                               
                                                                                      
╭─ Options ──────────────────────────────────────────────────────────────────────────╮
│ --help      Show this message and exit.                                            │
╰────────────────────────────────────────────────────────────────────────────────────╯
╭─ Commands ─────────────────────────────────────────────────────────────────────────╮
│ control    Manage control of NaviGator through external controllers.               │
│ rviz       Launch the NaviGator configuration for Rviz.                            │
│ thrust     Spin a THRUSTER on NaviGator with SETPOINT amount of thrust.            │
╰────────────────────────────────────────────────────────────────────────────────────╯

```

This project and each command will be implemented in Python to make the project code easier to read and implement. The tracking branch for the project will be `mil-cli` - members can branch off of this branch and make PRs back into it as needed.

<hr>

**How do you get started/get involved?** Just take on one of the tasks listed in the table below. Each task is focused on one individual command, for example, `mil nav control xbox`. For more of an intro on how to use Git, please see our [contributing guide](https://uf-mil.github.io/docs/software/contributing.html).

To set up your workspace to work on the CLI, complete the following steps:
1. `git checkout mil-cli`
2. `cd ~/catkin_ws/src/mil`
3. `./scripts/install.sh` (this installs the CLI for you)
4. `mil` - This should now be the CLI! You can run commands like `mil --help` or `mil bag record` now!

As you begin to make changes to the CLI files, they will be reflected **instantly** in the CLI installed in your workspace. You do not need to recompile anything to begin development.

<hr>

## Completion Table

Below is the **project completion table**. Each of the following commands needs to be implemented in the MIL CLI:

| Status | Command |
| --- | --- |
| ❌ | `mil bag record`
| ❌ (#912) | `mil bag retopic`
| ❌ (#913) | `mil docs build`
| ❌ (#914) | `mil mission list`
| ❌ (#915) | `mil mission run`
| ❌ (#916) | `mil mission refresh`
| ❌ (#927) | `mil nav control xbox`
| ❌ (#928) | `mil nav control keyboard`
| ❌ (#929) | `mil nav move`
| ❌ | `mil nav rviz`
| ❌ | `mil nav thrust`
| ❌ | `mil network listdevices`

**Comment by tringuyenswe** [comment]
Hi! I'm not sure if this has been worked on, but I was able to come up with multi-line bash commands, which I think is really useful and I don't see much good implementation online. I think I will be too busy next semester and can't work on anything for MIL, but I hope this is helpful for anyone trying to tackle this project. One thing to keep in mind is to remove all existing bash alias for like mil or nav or else this won't work and will just redirect to the old alias. Let me know if there are any questions : ) 

[multiline_bash_example.txt](https://github.com/uf-mil/mil/files/10340315/multiline_bash_example.txt)

**Comment by cbrxyz** [comment]
This issue is being closed until the repository is migrated to ROS 2 and is therefore compatible with Rust CLI tools.
